name: airbnbclone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: ManropeMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
